services:
  devcontainer:
    image: ccmagruder/devcontainer-symmetry:latest
    build:
      dockerfile: Dockerfile
      context: .devcontainer
    volumes:
      - type: bind
        source: .
        target: /root/symmetry
    working_dir: /root/symmetry
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
