name: Build and Publish Runpod Container

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-publish-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Symmetry Repo
        uses: actions/checkout@v3
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker Build Container
        run: docker build - < .runpod/Dockerfile --tag ccmagruder/runpod-symmetry --platform linux/amd64
      - name: Docker Push Container
        run: docker push ccmagruder/runpod-symmetry

